[project]
name = "ilm"
version = "2.0"
description = "Dave's ILM"
readme = "README.md"

requires-python = "==3.11.6"




dependencies = [
	"numpy ==1.26.4",
	"pandas >=1.2",

	"sympy ==1.13",
	"ply ==3.11",
	"Distance ==0.1.3",

]

[project.optional-dependencies]
extra = [
]
